### ISSUE TITLE
How to receive String instead of a float?

### ISSUE THREAD

**Issue by vettorazi** [is-centre/udp-ue4-plugin-win64#4]
First of all, thanks for your Plugin.
I'm trying to receive data from a UDP stream but instead of receiving ASCII, I just receive a float value. 
i.e: I am sending abcd and in UE I'm receiving a huge float like this 234123131241414.0
What I'm doing wrong?

**Comment by vettorazi** [comment]
Hi Aleksei,
I could edit the .h and rebuild the UDPData.h.
Although the way I changed the UPROPERTY didn't work.
`UPROPERTY(EditAnyWhere, BlueprintReadWrite, Category = "UDPCommunication")
		FString string1 = "testing";`

Can you help me?

**Comment by extall** [comment]
Exactly, that is because by default with basic datatypes like floats and uint8's. In real time communication with MATLAB/Simulink via Simulink Desktop Realtime toolbox this is what you want, and this is the main use case for this plugin.
However, it should also be possible to send/receive strings as well, it's just that sending/receiving sides should be able to pack and unpack this type of data (i.e., serialize it to the UDP packet payload and unserialize it later).
My suggestion is to try to figure out how something like this is done here: https://forums.unrealengine.com/development-discussion/c-gameplay-programming/25008-communication-between-ue4-and-a-python-udp-server
If you can later also suggest what changes should be done in this plugin to accommodate the above stated functionality, it would be a welcome contribution.

**Comment by johnsmakar** [comment]
Hello, I am trying to receive a string being sent from a microcontroller, but `IsNewDataReady` never returns true. What am I missing?

![image](https://user-images.githubusercontent.com/43448617/116972625-4e5ac280-ac89-11eb-8722-b234ab652a0c.png)

**Comment by extall** [comment]
It most likely never returns true because the socket does not receive anything. Please check your connection/routing/etc. Use something like Wireshark (https://www.wireshark.org/) to debug.
The code after the branch statement (Get String) will not work either, because this is not the way you get data via this plugin.
The plugin itself is intended more for sending simple datatypes such as double values or plain bytes, in real time. It is possible to send strings as well, but it is not well supported by default, you will need to change the data structure, its serialization, etc. within the plugin's C++ code.
So, for more complex communication tasks I recommend using something like https://github.com/getnamo/socketio-client-ue4

**Comment by johnsmakar** [comment]
Thanks for the reply. I can see that it is sending on Port 1234, regardless of the data I am sending (i.e. doubles or bytes) data ready never returns true. any my other microcontrollers receive the packet just fine.

I would like to keep it lightweight, so I want to hold off on using socket.io

**Comment by MSTIGM** [comment]
Hi,
Thank you so much for the plugin and the question...
Could you please add the possibility of sending/receiving "String" to your plugin for UE v4.26?
Your plugin is really awesome and very easy to understand and use comparing to other complex plugins such as SocketIO!
If you could add "String" to your plugin, it could be REALLY useful and great...
Thank you so much for your attentions.
With Kind Regards,
Stig
